# This is a Taskfile. It will help you do the things.
# https://taskfile.dev/#/installation

version: '3'

tasks:
  flash:
    desc: Compile the current configuration and flash the keyboard
    cmds:
      - >-
        make crkbd:manna-harbour_miryoku:flash
        AVR_CFLAGS="-Wno-array-bounds"
        MIRYOKU_ALPHAS=QWERTY
        MIRYOKU_NAV=VI
        MIRYOKU_TAP=QWERTY

  build:
    desc: Compile the current configuration without flashing
    cmds:
      - >-
        make crkbd:manna-harbour_miryoku
        AVR_CFLAGS="-Wno-array-bounds"
        MIRYOKU_ALPHAS=QWERTY
        MIRYOKU_NAV=VI
        MIRYOKU_TAP=QWERTY
