# This is a Taskfile. It will help you do the things.
# https://taskfile.dev/#/installation

version: '3'

tasks:
  flash:
    desc: Compile the current configuration and flash the keyboard
    cmds:
      - qmk flash -c -kb crkbd -km olivia5k

  build:
    desc: Compile the current configuration without flashing
    cmds:
      - qmk build -c -kb crkbd -km olivia5k
