#define MAX_DEFERRED_EXECUTORS 10

#define SMTD_GLOBAL_TAP_TERM 125
#define SMTD_GLOBAL_RELEASE_TERM 10

#define OLED_FONT_H "users/yasakbulut/glcdfont.c"

#define RGB_MATRIX_SPLIT { 27, 27 }

// If defined, the RGB lighting will be switched off when the host goes to sleep
#define RGB_MATRIX_SLEEP

#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON

#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define RGB_MATRIX_DEFAULT_SPD 31
#define RGB_MATRIX_DEFAULT_HUE 0
#define RGB_MATRIX_DEFAULT_SAT 128
#define RGB_MATRIX_DEFAULT_VAL 64

